### PR TITLE
Update CNTiCertification-2.0-beta.md

### PR DESCRIPTION
**Pull request by Smitholi67**
Simplified the documentation to a) be clearer about what certification tests are and b) linked to test documentation from the test suite to avoid duplication of efforts.

refs: #154

### CODE REVIEW

**Review by rich-l — APPROVED** [review]
lgtm

**Review by kosstennbl — APPROVED** [review]
LGTM, bits of information are lost (i.e. some info on disk_fill), but i don't consider this information as too valuable. Removal of redundancy with links to test documentation is great.

**Review by martin-mat — APPROVED** [review]
lgtm, as discussed - a new ticket to cnti-testcatalog/testsuite repo to review/add test information from here/certification repo there.

**Comment by Smitholi67** [comment]
New issue created to review the removed documentation and see if anything should be incorporated into the CNTi Test Catalog Test Documentation.  See https://github.com/cnti-testcatalog/testsuite/issues/2118

**Pull request merged**
